[build]
  command = "yarn build"
  publish = "frontend/build"

# Note: API calls must use REACT_APP_BACKEND_URL environment variable.
# Do not rely on Netlify redirects for API proxying per platform ingress rules.